import React, { useState, useCallback, useRef, useEffect } from "react";
import { View, Text, ScrollView, Pressable, TextInput, FlatList } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { IconSymbol } from "@/components/ui/icon-symbol";

interface AIAssistantFeature {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
}

interface ContentDraft {
  id: string;
  type: "post" | "clip" | "graph";
  title: string;
  content: string;
  createdAt: Date;
}

const AI_FEATURES: AIAssistantFeature[] = [
  {
    id: "search",
    name: "Real-Time Search",
    icon: "magnifyingglass",
    description: "Search trends, topics, and content ideas in real-time",
    color: "#3B82F6",
  },
  {
    id: "clip",
    name: "Video Clipping",
    icon: "scissors",
    description: "Auto-clip videos and suggest best moments",
    color: "#8B5CF6",
  },
  {
    id: "draft",
    name: "Post Drafting",
    icon: "pencil.and.notepad",
    description: "Draft social media posts and captions",
    color: "#EC4899",
  },
  {
    id: "graph",
    name: "Graph Generation",
    icon: "chart.bar.fill",
    description: "Generate analytics and performance graphs",
    color: "#10B981",
  },
  {
    id: "strategy",
    name: "Content Strategy",
    icon: "lightbulb.fill",
    description: "AI-powered content strategy recommendations",
    color: "#F59E0B",
  },
  {
    id: "schedule",
    name: "Scheduling",
    icon: "calendar",
    description: "Optimal posting times and scheduling",
    color: "#06B6D4",
  },
];

export default function CreatorAIAssistant() {
  const colors = useColors();
  const [isListening, setIsListening] = useState(false);
  const [voiceInput, setVoiceInput] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedFeature, setSelectedFeature] = useState<string | null>(null);
  const [drafts, setDrafts] = useState<ContentDraft[]>([]);
  const [showDrafts, setShowDrafts] = useState(false);
  const micRef = useRef<any>(null);

  // Simulate voice activation
  const handleMicPress = useCallback(() => {
    setIsListening(!isListening);
    if (!isListening) {
      // Simulate voice input
      setTimeout(() => {
        setVoiceInput("Create a post about fitness trends for this week");
      }, 1500);
    }
  }, [isListening]);

  // Handle feature selection
  const handleFeatureSelect = useCallback((featureId: string) => {
    setSelectedFeature(featureId);
    generateDraft(featureId);
  }, []);

  // Generate draft based on feature
  const generateDraft = (featureId: string) => {
    const feature = AI_FEATURES.find((f) => f.id === featureId);
    if (!feature) return;

    const draftContent: ContentDraft = {
      id: `draft_${Date.now()}`,
      type: featureId === "clip" ? "clip" : featureId === "graph" ? "graph" : "post",
      title: `${feature.name} - ${new Date().toLocaleDateString()}`,
      content: generateSampleContent(featureId),
      createdAt: new Date(),
    };

    setDrafts([draftContent, ...drafts]);
  };

  // Generate sample content based on feature
  const generateSampleContent = (featureId: string): string => {
    const samples: Record<string, string> = {
      search: "📊 Trending Topics This Week:\n1. AI in Content Creation\n2. Fitness Challenges\n3. Mental Health Awareness\n4. Tech Innovation\n5. Wellness Tips",
      clip: "🎬 Video Clip Suggestions:\n- Best moment: 2:45-3:15 (High engagement)\n- Highlight: 5:20-5:45 (Emotional peak)\n- Call-to-action: 7:00-7:30 (Conversion point)",
      draft: "✍️ Post Draft:\n'Just finished an amazing workout! Here's what I learned about consistency and discipline. Drop a 💪 if you&apos;re on your fitness journey too!'",
      graph: "📈 Performance Analytics:\n- Engagement Rate: +23% this week\n- Follower Growth: +156 new followers\n- Top Post: Fitness Tips (2.3K likes)\n- Best Time to Post: 6-8 PM",
      strategy: "💡 Content Strategy Recommendations:\n- Increase video content by 30%\n- Focus on trending hashtags\n- Collaborate with 2-3 creators\n- Post 4-5 times per week",
      schedule: "📅 Optimal Posting Schedule:\n- Monday: 6 PM (Motivation)\n- Wednesday: 7 PM (Tips)\n- Friday: 5 PM (Weekend prep)\n- Sunday: 8 PM (Weekly recap)",
    };
    return samples[featureId] || "Content generated by AI Assistant";
  };

  return (
    <ScreenContainer className="bg-background">
      <ScrollView contentContainerStyle={{ paddingBottom: 24 }}>
        {/* Header */}
        <View style={{ paddingHorizontal: 20, paddingVertical: 16, gap: 12 }}>
          <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}>
            <Text style={{ color: colors.foreground, fontSize: 28, fontWeight: "800" }}>
              Your AI Assistant
            </Text>
            <View
              style={{
                backgroundColor: colors.primary + "20",
                paddingHorizontal: 12,
                paddingVertical: 6,
                borderRadius: 999,
              }}
            >
              <Text style={{ color: colors.primary, fontSize: 12, fontWeight: "700" }}>BETA</Text>
            </View>
          </View>

          {/* Mic Button */}
          <Pressable
            onPress={handleMicPress}
            style={({ pressed }) => ({
              backgroundColor: isListening ? colors.error : colors.primary,
              paddingVertical: 16,
              borderRadius: 16,
              alignItems: "center",
              gap: 8,
              opacity: pressed ? 0.8 : 1,
            })}
          >
            <Text style={{ fontSize: 32 }}>{isListening ? "🎙️" : "🎤"}</Text>
            <Text style={{ color: "#FFFFFF", fontSize: 14, fontWeight: "600" }}>
              {isListening ? "Listening..." : "Tap to Activate Voice"}
            </Text>
            {voiceInput && (
              <Text style={{ color: "#FFFFFF", fontSize: 12, marginTop: 4, fontStyle: "italic" }}>
                &quot;{voiceInput}&quot;
              </Text>
            )}
          </Pressable>

          {/* Search Bar */}
          <View
            style={{
              flexDirection: "row",
              alignItems: "center",
              backgroundColor: colors.surface,
              borderRadius: 12,
              paddingHorizontal: 12,
              borderWidth: 1,
              borderColor: colors.border,
            }}
          >
            <IconSymbol name="magnifyingglass" size={20} color={colors.muted} />
            <TextInput
              value={searchQuery}
              onChangeText={setSearchQuery}
              placeholder="Ask your AI assistant..."
              placeholderTextColor={colors.muted}
              style={{
                flex: 1,
                paddingVertical: 12,
                paddingHorizontal: 8,
                fontSize: 14,
                color: colors.foreground,
              }}
            />
          </View>
        </View>

        {/* Features Grid */}
        <View style={{ paddingHorizontal: 20, gap: 12 }}>
          <Text style={{ color: colors.foreground, fontSize: 16, fontWeight: "700" }}>
            AI Tools
          </Text>
          <View style={{ gap: 10 }}>
            {AI_FEATURES.map((feature) => (
              <Pressable
                key={feature.id}
                onPress={() => handleFeatureSelect(feature.id)}
                style={({ pressed }) => ({
                  backgroundColor:
                    selectedFeature === feature.id
                      ? feature.color + "20"
                      : colors.surface,
                  borderWidth: selectedFeature === feature.id ? 2 : 1,
                  borderColor:
                    selectedFeature === feature.id ? feature.color : colors.border,
                  borderRadius: 12,
                  padding: 14,
                  flexDirection: "row",
                  alignItems: "center",
                  gap: 12,
                  opacity: pressed ? 0.7 : 1,
                })}
              >
                <View
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 10,
                    backgroundColor: feature.color + "20",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <IconSymbol
                    name={feature.icon as any}
                    size={22}
                    color={feature.color}
                  />
                </View>
                <View style={{ flex: 1, minWidth: 0 }}>
                  <Text
                    style={{
                      color: colors.foreground,
                      fontSize: 14,
                      fontWeight: "600",
                    }}
                  >
                    {feature.name}
                  </Text>
                  <Text
                    style={{
                      color: colors.muted,
                      fontSize: 12,
                      marginTop: 2,
                    }}
                    numberOfLines={1}
                  >
                    {feature.description}
                  </Text>
                </View>
                <IconSymbol
                  name="chevron.right"
                  size={20}
                  color={colors.muted}
                />
              </Pressable>
            ))}
          </View>
        </View>

        {/* Drafts Section */}
        {drafts.length > 0 && (
          <View style={{ paddingHorizontal: 20, marginTop: 24, gap: 12 }}>
            <Pressable
              onPress={() => setShowDrafts(!showDrafts)}
              style={{
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <Text style={{ color: colors.foreground, fontSize: 16, fontWeight: "700" }}>
                Drafts ({drafts.length})
              </Text>
              <IconSymbol
                name={showDrafts ? "chevron.up" : "chevron.down"}
                size={20}
                color={colors.muted}
              />
            </Pressable>

            {showDrafts && (
              <View style={{ gap: 10 }}>
                {drafts.map((draft) => (
                  <View
                    key={draft.id}
                    style={{
                      backgroundColor: colors.surface,
                      borderRadius: 12,
                      padding: 12,
                      borderWidth: 1,
                      borderColor: colors.border,
                      gap: 8,
                    }}
                  >
                    <View
                      style={{
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "space-between",
                      }}
                    >
                      <Text
                        style={{
                          color: colors.foreground,
                          fontSize: 13,
                          fontWeight: "600",
                        }}
                      >
                        {draft.title}
                      </Text>
                      <View
                        style={{
                          backgroundColor: colors.primary + "20",
                          paddingHorizontal: 8,
                          paddingVertical: 4,
                          borderRadius: 4,
                        }}
                      >
                        <Text
                          style={{
                            color: colors.primary,
                            fontSize: 10,
                            fontWeight: "700",
                          }}
                        >
                          {draft.type.toUpperCase()}
                        </Text>
                      </View>
                    </View>
                    <Text
                      style={{
                        color: colors.muted,
                        fontSize: 12,
                        lineHeight: 18,
                      }}
                      numberOfLines={3}
                    >
                      {draft.content}
                    </Text>
                    <View
                      style={{
                        flexDirection: "row",
                        gap: 8,
                        marginTop: 8,
                      }}
                    >
                      <Pressable
                        style={({ pressed }) => ({
                          flex: 1,
                          paddingVertical: 8,
                          borderRadius: 8,
                          backgroundColor: colors.primary,
                          alignItems: "center",
                          opacity: pressed ? 0.8 : 1,
                        })}
                      >
                        <Text
                          style={{
                            color: "#FFFFFF",
                            fontSize: 12,
                            fontWeight: "600",
                          }}
                        >
                          Use Draft
                        </Text>
                      </Pressable>
                      <Pressable
                        style={({ pressed }) => ({
                          flex: 1,
                          paddingVertical: 8,
                          borderRadius: 8,
                          backgroundColor: colors.surface,
                          borderWidth: 1,
                          borderColor: colors.border,
                          alignItems: "center",
                          opacity: pressed ? 0.8 : 1,
                        })}
                      >
                        <Text
                          style={{
                            color: colors.foreground,
                            fontSize: 12,
                            fontWeight: "600",
                          }}
                        >
                          Edit
                        </Text>
                      </Pressable>
                    </View>
                  </View>
                ))}
              </View>
            )}
          </View>
        )}

        {/* Info Box */}
        <View
          style={{
            marginHorizontal: 20,
            marginTop: 24,
            padding: 14,
            backgroundColor: colors.primary + "10",
            borderRadius: 12,
            borderLeftWidth: 4,
            borderLeftColor: colors.primary,
            gap: 6,
          }}
        >
          <Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "600" }}>
            💡 Tip
          </Text>
          <Text style={{ color: colors.muted, fontSize: 12, lineHeight: 16 }}>
            Your personal AI assistant is here to help you create better content faster. Use voice commands for hands-free operation, and all drafts are saved for later editing.
          </Text>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
