import { Stack } from "expo-router";
import { View, Text, Linking, Pressable } from "react-native";
import { ProfileStackScreen } from "@/components/profile-stack-screen";
import { useColors } from "@/hooks/use-colors";
import { TERMS_SUPPORT_EMAIL } from "@/lib/platform-terms-of-use";
import { getPlatformPublicOrigin } from "@/lib/platform-urls";

const FAQ = [
  {
    q: "How do I earn loyalty points?",
    a: "First sign-in: 500 LP welcome bonus plus your daily streak LP (100 + 10 × streak day — day 1 = 110 LP, day 30 = 400 LP). Sign in back-to-back every day to grow the bonus. Complete a 30-day streak and buy any AI plan during that run to unlock a free 1-day AI subscription. You can also earn points from posts, joining creators, and subscriptions — redeem in Profile.",
  },
  {
    q: "How do live AI classes work?",
    a: "Creators schedule paid group classes. Buy a ticket on the AI page, join the live room when it starts, and use voice or text question queues.",
  },
  {
    q: "Is AI content real people?",
    a: "No — all specialist AIs are generated by machine learning. See Settings for the full platform disclosure.",
  },
  {
    q: "Can I get a refund on AI subscriptions or credits?",
    a: "No. All AI specialist subscriptions, usage credits, talk time, and other digital access sold by UR Platform LLC are final — no returns and no refunds, including unused messages or credits.",
  },
  {
    q: "What about refunds from a content creator?",
    a: "Purchases from individual creators (live classes, shop items, etc.) are between you and that creator. UR Platform is not responsible for creator refunds or disputes. Contact the creator directly.",
  },
  {
    q: "What happens if someone harasses others on UR?",
    a: "Zero tolerance. Harassment may result in immediate suspension or ban. No refunds are issued when privileges are revoked for abuse. See Profile → Terms of Use.",
  },
  {
    q: "Who do I contact for billing?",
    a: "Email support with your account email and a description of the charge. Include the date and amount if you have it.",
  },
];

export default function ProfileHelpScreen() {
  const colors = useColors();
  const supportEmail = TERMS_SUPPORT_EMAIL;
  const platformUrl = getPlatformPublicOrigin();

  return (
    <>
      <Stack.Screen options={{ headerShown: false }} />
      <ProfileStackScreen
        title="Help & Support"
        subtitle="FAQs and how to reach us."
        icon="💬"
      >
        {FAQ.map((item) => (
          <View
            key={item.q}
            style={{
              borderRadius: 12,
              borderWidth: 1,
              borderColor: colors.border,
              backgroundColor: colors.surface,
              padding: 14,
              gap: 6,
            }}
          >
            <Text style={{ color: colors.foreground, fontWeight: "700" }}>{item.q}</Text>
            <Text style={{ color: colors.muted, fontSize: 13, lineHeight: 19 }}>{item.a}</Text>
          </View>
        ))}

        <View
          style={{
            borderRadius: 12,
            borderWidth: 1,
            borderColor: colors.primary,
            backgroundColor: `${colors.primary}10`,
            padding: 16,
            gap: 10,
          }}
        >
          <Text style={{ color: colors.foreground, fontWeight: "800" }}>Contact support</Text>
          <Pressable onPress={() => void Linking.openURL(`mailto:${supportEmail}`)}>
            <Text style={{ color: colors.primary, fontWeight: "600" }}>{supportEmail}</Text>
          </Pressable>
          <Pressable onPress={() => void Linking.openURL(platformUrl)}>
            <Text style={{ color: colors.muted, fontSize: 13 }}>{platformUrl}</Text>
          </Pressable>
        </View>
      </ProfileStackScreen>
    </>
  );
}
