import { Stack } from "expo-router";
import { View, Text, Linking, Pressable } from "react-native";
import { ProfileStackScreen } from "@/components/profile-stack-screen";
import { useColors } from "@/hooks/use-colors";
import { getPlatformPublicOrigin } from "@/lib/platform-urls";

const FAQ = [
  {
    q: "How do I earn loyalty points?",
    a: "Sign in daily from Profile for 200 points and scratch-off tickets. Use points for text messages with AIs.",
  },
  {
    q: "How do live AI classes work?",
    a: "Creators schedule paid group classes. Buy a ticket on the AI page, join the live room when it starts, and use voice or text question queues.",
  },
  {
    q: "Is AI content real people?",
    a: "No — all specialist AIs are generated by machine learning. See Settings for the full platform disclosure.",
  },
  {
    q: "Who do I contact for billing?",
    a: "Email support with your account email and a description of the charge. Include the date and amount if you have it.",
  },
];

export default function ProfileHelpScreen() {
  const colors = useColors();
  const supportEmail = "support@urplatform.llc";
  const platformUrl = getPlatformPublicOrigin();

  return (
    <>
      <Stack.Screen options={{ headerShown: false }} />
      <ProfileStackScreen
        title="Help & Support"
        subtitle="FAQs and how to reach us."
        icon="💬"
      >
        {FAQ.map((item) => (
          <View
            key={item.q}
            style={{
              borderRadius: 12,
              borderWidth: 1,
              borderColor: colors.border,
              backgroundColor: colors.surface,
              padding: 14,
              gap: 6,
            }}
          >
            <Text style={{ color: colors.foreground, fontWeight: "700" }}>{item.q}</Text>
            <Text style={{ color: colors.muted, fontSize: 13, lineHeight: 19 }}>{item.a}</Text>
          </View>
        ))}

        <View
          style={{
            borderRadius: 12,
            borderWidth: 1,
            borderColor: colors.primary,
            backgroundColor: `${colors.primary}10`,
            padding: 16,
            gap: 10,
          }}
        >
          <Text style={{ color: colors.foreground, fontWeight: "800" }}>Contact support</Text>
          <Pressable onPress={() => void Linking.openURL(`mailto:${supportEmail}`)}>
            <Text style={{ color: colors.primary, fontWeight: "600" }}>{supportEmail}</Text>
          </Pressable>
          <Pressable onPress={() => void Linking.openURL(platformUrl)}>
            <Text style={{ color: colors.muted, fontSize: 13 }}>{platformUrl}</Text>
          </Pressable>
        </View>
      </ProfileStackScreen>
    </>
  );
}
