import React from "react";
import { View, Text, Pressable } from "react-native";
import { useColors } from "@/hooks/use-colors";

export interface AIDisclosureWrapperProps {
  children: React.ReactNode;
  aiName: string;
  hasAffiliateLinks?: boolean;
  affiliateDisclosureText?: string;
  onDismiss?: () => void;
}

/**
 * AI Disclosure Wrapper Component
 * 
 * Wraps AI-generated content with mandatory before/after disclaimers.
 * Displays:
 * - BEFORE: "This is AI-generated content for entertainment/educational purposes"
 * - CONTENT: The actual AI content
 * - AFTER: Same disclaimer + affiliate disclosure if applicable
 * 
 * This ensures full legal compliance with FTC guidelines and entertainment disclaimers.
 */
export function AIDisclosureWrapper({
  children,
  aiName,
  hasAffiliateLinks = false,
  affiliateDisclosureText,
  onDismiss,
}: AIDisclosureWrapperProps) {
  const colors = useColors();

  return (
    <View style={{ gap: 12 }}>
      {/* BEFORE Disclosure */}
      <View
        style={{
          backgroundColor: colors.primary + "15",
          borderLeftWidth: 4,
          borderLeftColor: colors.primary,
          padding: 12,
          borderRadius: 8,
          gap: 6,
        }}
      >
        <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
          <Text style={{ fontSize: 16 }}>🤖</Text>
          <Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "600" }}>
            AI-Generated Content Disclosure
          </Text>
        </View>
        <Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16 }}>
          This content is generated by {aiName}, an AI assistant created by UR LLC. This content is for entertainment and educational purposes only and should not be considered professional advice.
        </Text>
        {hasAffiliateLinks && (
          <Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }}>
            ⚠️ This content may contain affiliate links. UR LLC and {aiName} may earn a commission if you click these links. Please review all links carefully before clicking.
          </Text>
        )}
      </View>

      {/* Content */}
      <View>{children}</View>

      {/* AFTER Disclosure */}
      <View
        style={{
          backgroundColor: colors.primary + "10",
          borderLeftWidth: 4,
          borderLeftColor: colors.primary,
          padding: 12,
          borderRadius: 8,
          gap: 6,
        }}
      >
        <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
          <Text style={{ fontSize: 16 }}>🤖</Text>
          <Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "600" }}>
            End of AI-Generated Content
          </Text>
        </View>
        <Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16 }}>
          The above content was generated by {aiName}. For more information about how UR handles AI-generated content, please review our Terms of Service and AI Disclosure Policy.
        </Text>
        {hasAffiliateLinks && affiliateDisclosureText && (
          <Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }}>
            {affiliateDisclosureText}
          </Text>
        )}
        {onDismiss && (
          <Pressable
            onPress={onDismiss}
            style={({ pressed }) => ({
              marginTop: 8,
              paddingVertical: 6,
              paddingHorizontal: 12,
              borderRadius: 6,
              backgroundColor: colors.primary + "20",
              opacity: pressed ? 0.6 : 1,
            })}
          >
            <Text style={{ color: colors.primary, fontSize: 12, fontWeight: "600", textAlign: "center" }}>
              Dismiss
            </Text>
          </Pressable>
        )}
      </View>
    </View>
  );
}
