import React from "react";
import { View, Text, Pressable, StyleSheet, type ViewStyle, type TextStyle } from "react-native";
import { useColors } from "@/hooks/use-colors";

export interface AIDisclosureWrapperProps {
  children: React.ReactNode;
  aiName: string;
  hasAffiliateLinks?: boolean;
  affiliateDisclosureText?: string;
  onDismiss?: () => void;
}

function DisclosureBlock({
  title,
  children,
  boxStyle,
  titleStyle,
  bodyStyle,
}: {
  title: string;
  children: React.ReactNode;
  boxStyle: ViewStyle;
  titleStyle: TextStyle;
  bodyStyle: TextStyle;
}) {
  return (
    <View style={boxStyle}>
      <View style={styles.titleRow}>
        <Text style={styles.emoji}>🤖</Text>
        <Text style={titleStyle}>{title}</Text>
      </View>
      <Text style={bodyStyle}>{children}</Text>
    </View>
  );
}

/**
 * Wraps AI-generated content with mandatory before/after disclaimers.
 */
export function AIDisclosureWrapper({
  children,
  aiName,
  hasAffiliateLinks = false,
  affiliateDisclosureText,
  onDismiss,
}: AIDisclosureWrapperProps) {
  const colors = useColors();

  const boxStyle: ViewStyle = {
    width: "100%",
    alignSelf: "stretch",
    flexShrink: 0,
    overflow: "hidden",
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    padding: 12,
    borderRadius: 8,
    gap: 8,
  };

  const titleStyle: TextStyle = {
    flex: 1,
    flexShrink: 1,
    color: colors.foreground,
    fontSize: 12,
    fontWeight: "600",
  };

  const bodyStyle: TextStyle = {
    width: "100%",
    flexShrink: 1,
    color: colors.muted,
    fontSize: 11,
    lineHeight: 17,
  };

  return (
    <View style={styles.root}>
      <DisclosureBlock
        title="AI-Generated Content Disclosure"
        boxStyle={{ ...boxStyle, backgroundColor: `${colors.primary}15` }}
        titleStyle={titleStyle}
        bodyStyle={bodyStyle}
      >
        {`This content is generated by ${aiName}, an AI assistant created by UR LLC. This content is for entertainment and educational purposes only and should not be considered professional advice.`}
        {hasAffiliateLinks
          ? `\n\nThis content may contain affiliate links. UR LLC and ${aiName} may earn a commission if you click these links. Please review all links carefully before clicking.`
          : ""}
      </DisclosureBlock>

      <View style={styles.contentSlot}>{children}</View>

      <DisclosureBlock
        title="End of AI-Generated Content"
        boxStyle={{ ...boxStyle, backgroundColor: `${colors.primary}10`, marginBottom: 4 }}
        titleStyle={titleStyle}
        bodyStyle={bodyStyle}
      >
        {`The above content was generated by ${aiName}. For more information about how UR handles AI-generated content, please review our Terms of Service and AI Disclosure Policy.`}
        {hasAffiliateLinks && affiliateDisclosureText
          ? `\n\n${affiliateDisclosureText}`
          : ""}
      </DisclosureBlock>

      {onDismiss ? (
        <Pressable
          onPress={onDismiss}
          style={({ pressed }) => ({
            marginTop: 4,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: 6,
            backgroundColor: `${colors.primary}20`,
            opacity: pressed ? 0.6 : 1,
          })}
        >
          <Text
            style={{
              color: colors.primary,
              fontSize: 12,
              fontWeight: "600",
              textAlign: "center",
            }}
          >
            Dismiss
          </Text>
        </Pressable>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    gap: 10,
  },
  contentSlot: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignSelf: "stretch",
    overflow: "hidden",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    width: "100%",
  },
  emoji: {
    fontSize: 16,
    lineHeight: 20,
  },
});
