import { View, Text, ScrollView, StyleSheet, Pressable } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useColors } from "@/hooks/use-colors";
import {
  PLATFORM_DISCLOSURE_FULL,
  PLATFORM_DISCLOSURE_SHORT,
} from "@/lib/platform-disclosure-copy";
import { brandDisclosureSurface, withAlpha } from "@/lib/brand-theme";

export interface WarningBannerProps {
  variant?: "default" | "compact";
  dismissible?: boolean;
  onDismiss?: () => void;
}

/**
 * Inline disclosure strip — matches the global frame styling (not a warning banner).
 */
export function WarningBanner({
  variant = "default",
  dismissible = false,
  onDismiss,
}: WarningBannerProps) {
  const colors = useColors();
  const brand = brandDisclosureSurface(colors);
  const message =
    variant === "compact" ? PLATFORM_DISCLOSURE_SHORT : PLATFORM_DISCLOSURE_FULL;

  return (
    <View style={[styles.bar, brand]}>
      <Text
        style={[styles.text, { color: withAlpha(colors.muted, 0.92), flex: 1 }]}
        numberOfLines={3}
      >
        {message}
      </Text>
      {dismissible && onDismiss ? (
        <Pressable onPress={onDismiss} hitSlop={8} accessibilityLabel="Dismiss disclosure">
          <Text style={[styles.dismiss, { color: colors.muted }]}>×</Text>
        </Pressable>
      ) : null}
    </View>
  );
}

/**
 * Full disclosure detail — settings / legal screens.
 */
export function WarningDisclosureModal() {
  const colors = useColors();

  return (
    <View
      style={[
        styles.modal,
        { backgroundColor: colors.surface, borderColor: colors.border },
      ]}
    >
      <Text style={[styles.modalTitle, { color: colors.foreground }]}>
        Platform disclosure
      </Text>

      <ScrollView style={styles.modalScroll}>
        <View style={styles.modalSection}>
          <Text style={[styles.sectionTitle, { color: colors.foreground }]}>
            AI-generated content
          </Text>
          <Text style={[styles.sectionBody, { color: colors.muted }]}>
            This platform contains interactions with artificial intelligence (AI) powered
            personas. These are not real people and responses are generated by machine
            learning models. AI-generated content may contain inaccuracies, outdated
            information, or errors.
          </Text>
        </View>

        <View style={styles.modalSection}>
          <Text style={[styles.sectionTitle, { color: colors.foreground }]}>
            Affiliate links & commissions
          </Text>
          <Text style={[styles.sectionBody, { color: colors.muted }]}>
            This platform may contain affiliate links to third-party services. UR Platform LLC may
            receive commissions from purchases made through these links. These commissions
            do not affect your purchase price.
          </Text>
        </View>

        <View style={styles.modalSection}>
          <Text style={[styles.sectionTitle, { color: colors.foreground }]}>
            Not professional advice
          </Text>
          <Text style={[styles.sectionBody, { color: colors.muted }]}>
            Content provided by creators or AI personas is for educational and recreational
            purposes only. It is not professional medical, legal, or financial advice. Always
            consult qualified professionals before making important decisions.
          </Text>
        </View>

        <View style={styles.modalSection}>
          <Text style={[styles.sectionTitle, { color: colors.foreground }]}>
            Your responsibility
          </Text>
          <Text style={[styles.sectionBody, { color: colors.muted }]}>
            Users are solely responsible for verifying information and making independent
            decisions. UR Platform LLC is not liable for any losses or consequences resulting from
            reliance on platform content.
          </Text>
        </View>

        <View style={styles.modalSection}>
          <Text style={[styles.sectionTitle, { color: colors.foreground }]}>
            Age requirement
          </Text>
          <Text style={[styles.sectionBody, { color: colors.muted }]}>
            This platform is only available to users 18 years of age or older.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

/** Sticky web header — same calm styling as native. */
export function WebWarningBanner() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const brand = brandDisclosureSurface(colors);

  return (
    <View style={[styles.webBar, brand, { paddingTop: insets.top + 4, paddingBottom: 5 }]}>
      <Text style={[styles.text, { color: withAlpha(colors.muted, 0.92) }]}>
        {PLATFORM_DISCLOSURE_SHORT}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  bar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  text: {
    fontSize: 10,
    fontWeight: "400",
    lineHeight: 14,
    textAlign: "center",
    letterSpacing: 0.15,
    opacity: 0.72,
  },
  dismiss: {
    fontSize: 18,
    lineHeight: 20,
    opacity: 0.5,
    paddingHorizontal: 4,
  },
  modal: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 20,
    gap: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
  },
  modalScroll: {
    maxHeight: 384,
  },
  modalSection: {
    gap: 6,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "600",
  },
  sectionBody: {
    fontSize: 13,
    lineHeight: 20,
  },
  webBar: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
});
