import { View, Text, ScrollView } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { cn } from "@/lib/utils";

export interface WarningBannerProps {
  variant?: "default" | "compact";
  dismissible?: boolean;
  onDismiss?: () => void;
}

/**
 * Persistent Warning Banner Component
 * Displays on every page from initial landing through signup
 * Shows AI interaction and affiliate disclosure
 */
export function WarningBanner({
  variant = "default",
  dismissible = false,
  onDismiss,
}: WarningBannerProps) {
  const colors = useColors();

  const defaultMessage =
    "⚠️ Notice: Interaction with synthetic AI personas. Responses may contain affiliate links yielding commissions to UR LLC. Provided strictly for educational/recreational purposes.";

  const compactMessage =
    "⚠️ AI Content & Affiliate Disclosure: See full notice in settings.";

  const message = variant === "compact" ? compactMessage : defaultMessage;

  return (
    <View className="bg-yellow-400 border-b-2 border-yellow-600 px-4 py-3">
      <View className="flex-row items-center justify-between gap-2">
        <Text className="text-sm font-bold text-black flex-1">{message}</Text>
        {dismissible && onDismiss && (
          <Text
            onPress={onDismiss}
            className="text-black font-bold text-lg ml-2"
          >
            ✕
          </Text>
        )}
      </View>
    </View>
  );
}

/**
 * Full Warning Disclosure Modal
 * Shows complete legal notice
 */
export function WarningDisclosureModal() {
  const colors = useColors();

  return (
    <View className="bg-surface rounded-lg border border-border p-6 gap-4">
      <Text className="text-2xl font-bold text-foreground">⚠️ Important Notice</Text>

      <ScrollView className="max-h-96 gap-4">
        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            AI-Generated Content & Synthetic Personas
          </Text>
          <Text className="text-sm text-muted">
            This platform contains interactions with artificial intelligence (AI) powered personas. These are not real people and responses are generated by machine learning models. AI-generated content may contain inaccuracies, outdated information, or errors.
          </Text>
        </View>

        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            Affiliate Links & Commissions
          </Text>
          <Text className="text-sm text-muted">
            This platform may contain affiliate links to third-party services (Amazon, Walmart, etc.). UR LLC may receive commissions from purchases made through these links. These commissions do not affect your purchase price.
          </Text>
        </View>

        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            Not Medical, Legal, or Financial Advice
          </Text>
          <Text className="text-sm text-muted">
            Content provided by creators or AI personas is for educational and recreational purposes only. It is NOT professional medical, legal, or financial advice. Always consult qualified professionals before making important decisions.
          </Text>
        </View>

        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            User Responsibility
          </Text>
          <Text className="text-sm text-muted">
            Users are solely responsible for verifying information, conducting due diligence, and making independent decisions. UR LLC is not liable for any losses, damages, or consequences resulting from reliance on platform content.
          </Text>
        </View>

        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            Age Requirement
          </Text>
          <Text className="text-sm text-muted">
            This platform is only available to users 18 years of age or older. By using this platform, you confirm that you are at least 18 years old and have verified your identity.
          </Text>
        </View>

        <View className="gap-2">
          <Text className="text-lg font-bold text-foreground">
            Terms of Service
          </Text>
          <Text className="text-sm text-muted">
            By accessing this platform, you agree to our Terms of Service, Privacy Policy, and all applicable legal notices. You assume all risks associated with using this platform.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

/**
 * Compact Warning Banner for Web
 * Sticky header version for web pages
 */
export function WebWarningBanner() {
  return (
    <View className="sticky top-0 z-50 bg-yellow-400 border-b-2 border-yellow-600 px-4 py-2">
      <Text className="text-sm font-bold text-black text-center">
        ⚠️ Notice: Interaction with synthetic AI personas. Responses may contain affiliate links yielding commissions to UR LLC. Provided strictly for educational/recreational purposes.
      </Text>
    </View>
  );
}
