/**
 * AI Disclosure Service
 * 
 * Manages all AI disclosure requirements across the platform.
 * Ensures every AI-generated content has proper before/after disclaimers.
 * Tracks affiliate links and generates appropriate disclosures.
 */

export interface AIContentMetadata {
  aiId: string;
  aiName: string;
  contentType: "post" | "comment" | "message" | "recommendation" | "analysis";
  hasAffiliateLinks: boolean;
  affiliateLinks?: string[];
  createdAt: Date;
  creatorId?: string;
  isCreatorPersonalAI?: boolean;
}

export interface AIDisclosureRequirements {
  beforeDisclosure: string;
  afterDisclosure: string;
  affiliateWarning?: string;
  entertainmentDisclaimer: string;
}

/**
 * Generate disclosure requirements for AI content
 */
export function generateAIDisclosures(metadata: AIContentMetadata): AIDisclosureRequirements {
  const { aiName, hasAffiliateLinks, contentType, isCreatorPersonalAI } = metadata;

  const baseEntity = isCreatorPersonalAI ? `${aiName} (Creator's Personal AI)` : aiName;

  const beforeDisclosure = `🤖 AI-Generated Content Disclosure\n\nThis ${contentType} is generated by ${baseEntity}, an AI assistant created by UR LLC. This content is for entertainment and educational purposes only and should not be considered professional advice.${
    hasAffiliateLinks
      ? "\n\n⚠️ This content may contain affiliate links. UR LLC and ${baseEntity} may earn a commission if you click these links."
      : ""
  }`;

  const afterDisclosure = `🤖 End of AI-Generated Content\n\nThe above ${contentType} was generated by ${baseEntity}. For more information about how UR handles AI-generated content, please review our Terms of Service and AI Disclosure Policy.`;

  const entertainmentDisclaimer =
    "This content is provided for entertainment and educational purposes only. It should not be relied upon for professional advice, medical decisions, financial advice, or legal guidance.";

  const affiliateWarning = hasAffiliateLinks
    ? `Affiliate Disclosure: This content contains affiliate links. If you purchase through these links, ${baseEntity} and UR LLC may earn a commission at no additional cost to you.`
    : undefined;

  return {
    beforeDisclosure,
    afterDisclosure,
    affiliateWarning,
    entertainmentDisclaimer,
  };
}

/**
 * Validate AI content for disclosure compliance
 */
export function validateAIContentCompliance(
  content: string,
  metadata: AIContentMetadata,
  hasBeforeDisclosure: boolean,
  hasAfterDisclosure: boolean
): { isCompliant: boolean; missingDisclosures: string[] } {
  const missingDisclosures: string[] = [];

  if (!hasBeforeDisclosure) {
    missingDisclosures.push("BEFORE disclosure missing");
  }

  if (!hasAfterDisclosure) {
    missingDisclosures.push("AFTER disclosure missing");
  }

  if (metadata.hasAffiliateLinks && !content.includes("affiliate")) {
    missingDisclosures.push("Affiliate link disclosure missing");
  }

  return {
    isCompliant: missingDisclosures.length === 0,
    missingDisclosures,
  };
}

/**
 * Extract affiliate links from content
 */
export function extractAffiliateLinks(content: string): string[] {
  const urlRegex = /(https?:\/\/[^\s]+)/g;
  const matches = content.match(urlRegex) || [];
  return matches.filter((url) => {
    const affiliateKeywords = ["amazon", "walmart", "ebay", "affiliate", "aff", "ref"];
    return affiliateKeywords.some((keyword) => url.toLowerCase().includes(keyword));
  });
}

/**
 * Format AI content with mandatory disclosures
 */
export function formatAIContentWithDisclosures(
  content: string,
  metadata: AIContentMetadata
): { formattedContent: string; disclosures: AIDisclosureRequirements } {
  const disclosures = generateAIDisclosures(metadata);

  const formattedContent = `${disclosures.beforeDisclosure}\n\n${content}\n\n${disclosures.afterDisclosure}`;

  return {
    formattedContent,
    disclosures,
  };
}

/**
 * Log AI content for compliance audit trail
 */
export interface AIContentAuditLog {
  id: string;
  aiId: string;
  contentId: string;
  contentType: string;
  hasBeforeDisclosure: boolean;
  hasAfterDisclosure: boolean;
  hasAffiliateLinks: boolean;
  isCompliant: boolean;
  timestamp: Date;
  creatorId?: string;
}

export const AIContentAuditLogs: AIContentAuditLog[] = [];

export function logAIContent(
  aiId: string,
  contentId: string,
  metadata: AIContentMetadata,
  hasBeforeDisclosure: boolean,
  hasAfterDisclosure: boolean
): AIContentAuditLog {
  const log: AIContentAuditLog = {
    id: `audit_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    aiId,
    contentId,
    contentType: metadata.contentType,
    hasBeforeDisclosure,
    hasAfterDisclosure,
    hasAffiliateLinks: metadata.hasAffiliateLinks,
    isCompliant: hasBeforeDisclosure && hasAfterDisclosure,
    timestamp: new Date(),
    creatorId: metadata.creatorId,
  };

  AIContentAuditLogs.push(log);
  return log;
}

/**
 * Get compliance report for AI content
 */
export function getAIComplianceReport(aiId?: string, creatorId?: string) {
  let logs = AIContentAuditLogs;

  if (aiId) {
    logs = logs.filter((log) => log.aiId === aiId);
  }

  if (creatorId) {
    logs = logs.filter((log) => log.creatorId === creatorId);
  }

  const totalContent = logs.length;
  const compliantContent = logs.filter((log) => log.isCompliant).length;
  const complianceRate = totalContent > 0 ? (compliantContent / totalContent) * 100 : 0;

  return {
    totalContent,
    compliantContent,
    nonCompliantContent: totalContent - compliantContent,
    complianceRate: complianceRate.toFixed(2) + "%",
    logs,
  };
}
