/**
 * AI Subscription Pitch Engine
 * Generates intelligent, compliant subscription pitches based on audience analysis
 * Ensures AI disclosure, compliance messaging, and UR LLC revenue tracking
 */

export interface SubscriptionPitch {
  pitchId: string;
  creatorId: string;
  userId: string;
  aiDisclosurePrePitch: string;
  mainPitch: string;
  benefitsHighlight: string[];
  callToAction: string;
  aiDisclosurePostPitch: string;
  complianceDisclaimer: string;
  recommendedTier: 'silver' | 'gold' | 'platinum';
  estimatedValue: number;
  timestamp: Date;
  urLLCRevenueShare: number;
}

export interface PitchContext {
  userId: string;
  creatorId: string;
  creatorName: string;
  creatorSpecialty: string;
  userEngagementScore: number;
  userInterests: string[];
  subscriptionReadiness: 'cold' | 'warm' | 'hot';
  conversionProbability: number;
  preferredContentType: string;
}

class AISubscriptionPitchEngine {
  private pitchHistory: Map<string, SubscriptionPitch[]> = new Map();
  private pitchMetrics: Map<string, { sent: number; converted: number; revenue: number }> = new Map();

  /**
   * Generate subscription pitch
   */
  generatePitch(context: PitchContext, creatorAbilities: string[]): SubscriptionPitch {
    const pitchId = `pitch_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // AI Disclosure - BEFORE pitch
    const aiDisclosurePrePitch = this.generatePrePitchDisclosure(context.creatorName);

    // Main pitch
    const mainPitch = this.generateMainPitch(context, creatorAbilities);

    // Benefits highlight
    const benefitsHighlight = this.generateBenefits(context, creatorAbilities);

    // Call to action
    const callToAction = this.generateCallToAction(context);

    // AI Disclosure - AFTER pitch
    const aiDisclosurePostPitch = this.generatePostPitchDisclosure();

    // Compliance disclaimer
    const complianceDisclaimer = this.generateComplianceDisclaimer();

    // Recommended tier
    const recommendedTier = this.recommendTier(context);

    // Estimated value
    const estimatedValue = this.estimateValue(recommendedTier);

    // UR LLC revenue share (hardcoded: 30%)
    const urLLCRevenueShare = estimatedValue * 0.30;

    const pitch: SubscriptionPitch = {
      pitchId,
      creatorId: context.creatorId,
      userId: context.userId,
      aiDisclosurePrePitch,
      mainPitch,
      benefitsHighlight,
      callToAction,
      aiDisclosurePostPitch,
      complianceDisclaimer,
      recommendedTier,
      estimatedValue,
      timestamp: new Date(),
      urLLCRevenueShare,
    };

    // Track pitch
    this.trackPitch(pitch);

    return pitch;
  }

  /**
   * Generate pre-pitch AI disclosure
   */
  private generatePrePitchDisclosure(creatorName: string): string {
    return `⚠️ **AI DISCLOSURE**: You are about to interact with ${creatorName}, an artificial intelligence created by UR LLC. This is an AI-powered experience designed for entertainment and educational purposes only. ${creatorName} is not a real person and all responses are generated by artificial intelligence.`;
  }

  /**
   * Generate main pitch
   */
  private generateMainPitch(context: PitchContext, abilities: string[]): string {
    const pitchTemplates = [
      `I've noticed you're really interested in ${context.userInterests[0] || 'my content'}! I think you'd get amazing value from a subscription. Here's why:`,
      `Based on your engagement, I think a subscription would unlock features you'd love. Let me show you what you'd get:`,
      `You've been such an engaged follower! I want to give you access to my premium content and exclusive features:`,
      `I can tell you're passionate about ${context.userInterests[0] || 'this topic'}. My subscription tier would give you:`,
    ];

    return pitchTemplates[Math.floor(Math.random() * pitchTemplates.length)];
  }

  /**
   * Generate benefits
   */
  private generateBenefits(context: PitchContext, abilities: string[]): string[] {
    const benefits: string[] = [];

    // Add ability-specific benefits
    for (const ability of abilities.slice(0, 3)) {
      benefits.push(`✅ Full access to ${ability}`);
    }

    // Add tier-specific benefits
    if (context.subscriptionReadiness === 'hot') {
      benefits.push('✅ Priority support and personalized responses');
      benefits.push('✅ Exclusive content and early access to new features');
      benefits.push('✅ Ad-free experience');
    } else if (context.subscriptionReadiness === 'warm') {
      benefits.push('✅ Access to premium features');
      benefits.push('✅ Faster response times');
    }

    // Add engagement-based benefits
    if (context.userEngagementScore > 50) {
      benefits.push('✅ Special member-only sessions and Q&A');
    }

    return benefits;
  }

  /**
   * Generate call to action
   */
  private generateCallToAction(context: PitchContext): string {
    const tier = this.recommendTier(context);
    const tierPrices: Record<string, string> = {
      silver: '$9.99/month',
      gold: '$24.99/month',
      platinum: '$99.99/month',
    };

    const ctaTemplates = [
      `Ready to level up? Subscribe to my ${tier} tier for ${tierPrices[tier]} and unlock everything above.`,
      `I'd love to have you as a subscriber! Click below to join my ${tier} community.`,
      `Your ${tier} subscription is waiting. Join thousands of satisfied members today!`,
    ];

    return ctaTemplates[Math.floor(Math.random() * ctaTemplates.length)];
  }

  /**
   * Generate post-pitch AI disclosure
   */
  private generatePostPitchDisclosure(): string {
    return `\n\n⚠️ **AI REMINDER**: This pitch was generated by an AI. The subscription offer is real and managed by UR LLC, but this message itself is AI-created. For questions about your subscription, please contact UR LLC support.`;
  }

  /**
   * Generate compliance disclaimer
   */
  private generateComplianceDisclaimer(): string {
    return `**COMPLIANCE NOTICE**: This content is for entertainment and educational purposes only. UR LLC is not liable for any claims or disputes arising from this AI interaction. By subscribing, you acknowledge that you are interacting with an artificial intelligence. All transactions are processed by UR LLC. Refund policy applies per UR LLC terms of service.`;
  }

  /**
   * Recommend subscription tier
   */
  private recommendTier(context: PitchContext): 'silver' | 'gold' | 'platinum' {
    if (context.conversionProbability > 80) {
      return 'platinum';
    } else if (context.conversionProbability > 60) {
      return 'gold';
    } else {
      return 'silver';
    }
  }

  /**
   * Estimate subscription value
   */
  private estimateValue(tier: 'silver' | 'gold' | 'platinum'): number {
    const tierValues: Record<string, number> = {
      silver: 9.99,
      gold: 24.99,
      platinum: 99.99,
    };
    return tierValues[tier];
  }

  /**
   * Track pitch
   */
  private trackPitch(pitch: SubscriptionPitch): void {
    const key = `${pitch.creatorId}`;

    if (!this.pitchHistory.has(key)) {
      this.pitchHistory.set(key, []);
    }

    this.pitchHistory.get(key)!.push(pitch);

    // Initialize metrics if needed
    if (!this.pitchMetrics.has(key)) {
      this.pitchMetrics.set(key, { sent: 0, converted: 0, revenue: 0 });
    }

    const metrics = this.pitchMetrics.get(key)!;
    metrics.sent++;
  }

  /**
   * Record pitch conversion
   */
  recordConversion(pitchId: string, creatorId: string, subscriptionAmount: number): void {
    const key = `${creatorId}`;
    const metrics = this.pitchMetrics.get(key);

    if (metrics) {
      metrics.converted++;
      metrics.revenue += subscriptionAmount;
    }
  }

  /**
   * Get pitch metrics
   */
  getPitchMetrics(creatorId: string): { sent: number; converted: number; conversionRate: number; revenue: number; urLLCShare: number } {
    const key = `${creatorId}`;
    const metrics = this.pitchMetrics.get(key) || { sent: 0, converted: 0, revenue: 0 };

    const conversionRate = metrics.sent > 0 ? (metrics.converted / metrics.sent) * 100 : 0;
    const urLLCShare = metrics.revenue * 0.30; // 30% to UR LLC

    return {
      sent: metrics.sent,
      converted: metrics.converted,
      conversionRate: Math.round(conversionRate * 100) / 100,
      revenue: Math.round(metrics.revenue * 100) / 100,
      urLLCShare: Math.round(urLLCShare * 100) / 100,
    };
  }

  /**
   * Get pitch history
   */
  getPitchHistory(creatorId: string): SubscriptionPitch[] {
    return this.pitchHistory.get(creatorId) || [];
  }

  /**
   * Generate compliance-compliant pitch summary
   */
  generateComplianceSummary(pitch: SubscriptionPitch): string {
    return `${pitch.aiDisclosurePrePitch}\n\n${pitch.mainPitch}\n\n${pitch.benefitsHighlight.join('\n')}\n\n${pitch.callToAction}\n\n${pitch.aiDisclosurePostPitch}\n\n${pitch.complianceDisclaimer}`;
  }

  /**
   * Validate pitch for compliance
   */
  validatePitchCompliance(pitch: SubscriptionPitch): { compliant: boolean; issues: string[] } {
    const issues: string[] = [];

    if (!pitch.aiDisclosurePrePitch.includes('AI')) {
      issues.push('Missing pre-pitch AI disclosure');
    }

    if (!pitch.aiDisclosurePostPitch.includes('AI')) {
      issues.push('Missing post-pitch AI disclosure');
    }

    if (!pitch.complianceDisclaimer.includes('entertainment')) {
      issues.push('Missing entertainment/educational purpose disclaimer');
    }

    if (!pitch.complianceDisclaimer.includes('UR LLC')) {
      issues.push('Missing UR LLC identification');
    }

    if (pitch.urLLCRevenueShare === 0) {
      issues.push('UR LLC revenue share not calculated');
    }

    return {
      compliant: issues.length === 0,
      issues,
    };
  }
}

export const aiSubscriptionPitchEngine = new AISubscriptionPitchEngine();
