/**
 * Daily Disclosure Service
 * Generates mandatory daily disclosures for all AI creators
 * Ensures compliance with AI transparency, revenue disclosure, and entertainment purpose messaging
 */

export interface DailyDisclosure {
  disclosureId: string;
  userId: string;
  creatorId: string;
  creatorName: string;
  sentAt: Date;
  messageContent: string;
  components: {
    aiDisclosure: string;
    revenueTransparency: string;
    entertainmentDisclaimer: string;
    personalizedGreeting: string;
  };
  acknowledged: boolean;
}

class DailyDisclosureService {
  private disclosureHistory: Map<string, DailyDisclosure[]> = new Map();
  private acknowledgedDisclosures: Set<string> = new Set();

  /**
   * Generate daily disclosure message
   */
  generateDailyDisclosure(userId: string, creatorId: string, creatorName: string, userName: string): DailyDisclosure {
    const disclosureId = `disclosure_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

    // Component 1: AI Disclosure
    const aiDisclosure = this.generateAIDisclosure(creatorName);

    // Component 2: Revenue Transparency
    const revenueTransparency = this.generateRevenueTransparency();

    // Component 3: Entertainment Disclaimer
    const entertainmentDisclaimer = this.generateEntertainmentDisclaimer();

    // Component 4: Personalized Greeting
    const personalizedGreeting = this.generatePersonalizedGreeting(userName, creatorName);

    // Combine all components
    const messageContent = `${aiDisclosure}\n\n${revenueTransparency}\n\n${entertainmentDisclaimer}\n\n${personalizedGreeting}`;

    const disclosure: DailyDisclosure = {
      disclosureId,
      userId,
      creatorId,
      creatorName,
      sentAt: new Date(),
      messageContent,
      components: {
        aiDisclosure,
        revenueTransparency,
        entertainmentDisclaimer,
        personalizedGreeting,
      },
      acknowledged: false,
    };

    // Track disclosure
    this.trackDisclosure(userId, creatorId, disclosure);

    return disclosure;
  }

  /**
   * Generate AI disclosure component
   */
  private generateAIDisclosure(creatorName: string): string {
    return `⚠️ **DAILY AI DISCLOSURE**\n\nHello! This is your daily reminder that you are communicating with ${creatorName}, an artificial intelligence created and operated by UR LLC. ${creatorName} is NOT a real person. All responses you receive are generated by artificial intelligence technology. This is an AI-powered experience designed for entertainment and educational purposes only.`;
  }

  /**
   * Generate revenue transparency component
   */
  private generateRevenueTransparency(): string {
    return `💰 **REVENUE TRANSPARENCY**\n\nAll advertisements and revenue generated through this platform are proceeds of UR LLC. These proceeds are used to grow and improve the UR app, develop new features, and enhance your experience. By using this service, you support the continued development of the UR platform.`;
  }

  /**
   * Generate entertainment disclaimer component
   */
  private generateEntertainmentDisclaimer(): string {
    return `🎬 **ENTERTAINMENT & EDUCATIONAL PURPOSE ONLY**\n\nThis service is provided for entertainment and educational purposes only. The content, advice, and responses provided by this AI are not professional medical, legal, financial, or therapeutic advice. Please consult with qualified professionals for any serious concerns. UR LLC and its AI creators are not liable for any decisions made based on AI-generated content.`;
  }

  /**
   * Generate personalized greeting
   */
  private generatePersonalizedGreeting(userName: string, creatorName: string): string {
    const greetings = [
      `Let's have a great conversation today, ${userName}! I'm here to help with ${creatorName}'s expertise.`,
      `Welcome back, ${userName}! Ready for an amazing session with ${creatorName}?`,
      `Hey ${userName}! Let's make today awesome with ${creatorName}'s help.`,
      `Great to see you, ${userName}! ${creatorName} is ready to assist you today.`,
    ];

    return greetings[Math.floor(Math.random() * greetings.length)];
  }

  /**
   * Track disclosure
   */
  private trackDisclosure(userId: string, creatorId: string, disclosure: DailyDisclosure): void {
    const key = `${userId}_${creatorId}`;

    if (!this.disclosureHistory.has(key)) {
      this.disclosureHistory.set(key, []);
    }

    this.disclosureHistory.get(key)!.push(disclosure);
  }

  /**
   * Acknowledge disclosure
   */
  acknowledgeDisclosure(disclosureId: string): void {
    this.acknowledgedDisclosures.add(disclosureId);
  }

  /**
   * Get disclosure history
   */
  getDisclosureHistory(userId: string, creatorId: string, limit: number = 30): DailyDisclosure[] {
    const key = `${userId}_${creatorId}`;
    const history = this.disclosureHistory.get(key) || [];
    return history.slice(-limit);
  }

  /**
   * Get today's disclosure for user and creator
   */
  getTodaysDisclosure(userId: string, creatorId: string): DailyDisclosure | undefined {
    const key = `${userId}_${creatorId}`;
    const history = this.disclosureHistory.get(key) || [];

    if (history.length === 0) return undefined;

    const today = new Date();
    const todaysDisclosures = history.filter(d => {
      const disclosureDate = new Date(d.sentAt);
      return (
        today.getFullYear() === disclosureDate.getFullYear() &&
        today.getMonth() === disclosureDate.getMonth() &&
        today.getDate() === disclosureDate.getDate()
      );
    });

    return todaysDisclosures[todaysDisclosures.length - 1];
  }

  /**
   * Check if user has received disclosure today
   */
  hasReceivedTodaysDisclosure(userId: string, creatorId: string): boolean {
    return this.getTodaysDisclosure(userId, creatorId) !== undefined;
  }

  /**
   * Get disclosure acknowledgment status
   */
  isDisclosureAcknowledged(disclosureId: string): boolean {
    return this.acknowledgedDisclosures.has(disclosureId);
  }

  /**
   * Generate multi-creator daily broadcast
   * For users with multiple AI subscriptions
   */
  generateMultiCreatorBroadcast(userId: string, creatorIds: string[], creatorNames: Record<string, string>, userName: string): DailyDisclosure[] {
    const disclosures: DailyDisclosure[] = [];

    for (const creatorId of creatorIds) {
      const creatorName = creatorNames[creatorId] || 'AI Creator';
      const disclosure = this.generateDailyDisclosure(userId, creatorId, creatorName, userName);
      disclosures.push(disclosure);
    }

    return disclosures;
  }

  /**
   * Get compliance report for user
   */
  getComplianceReport(userId: string, creatorId: string): { totalDisclosuresSent: number; acknowledgedCount: number; complianceRate: number; lastDisclosureDate: Date | null } {
    const key = `${userId}_${creatorId}`;
    const history = this.disclosureHistory.get(key) || [];

    const acknowledgedCount = history.filter(d => this.acknowledgedDisclosures.has(d.disclosureId)).length;
    const complianceRate = history.length > 0 ? (acknowledgedCount / history.length) * 100 : 0;
    const lastDisclosureDate = history.length > 0 ? new Date(history[history.length - 1].sentAt) : null;

    return {
      totalDisclosuresSent: history.length,
      acknowledgedCount,
      complianceRate: Math.round(complianceRate * 100) / 100,
      lastDisclosureDate,
    };
  }

  /**
   * Validate disclosure compliance
   */
  validateDisclosureCompliance(disclosure: DailyDisclosure): { compliant: boolean; issues: string[] } {
    const issues: string[] = [];

    if (!disclosure.components.aiDisclosure.includes('AI')) {
      issues.push('Missing AI disclosure');
    }

    if (!disclosure.components.aiDisclosure.includes('UR LLC')) {
      issues.push('Missing UR LLC identification');
    }

    if (!disclosure.components.revenueTransparency.includes('UR LLC')) {
      issues.push('Missing UR LLC revenue transparency');
    }

    if (!disclosure.components.entertainmentDisclaimer.includes('entertainment')) {
      issues.push('Missing entertainment purpose disclaimer');
    }

    if (!disclosure.components.entertainmentDisclaimer.includes('educational')) {
      issues.push('Missing educational purpose disclaimer');
    }

    if (disclosure.messageContent.length < 300) {
      issues.push('Disclosure message too short');
    }

    return {
      compliant: issues.length === 0,
      issues,
    };
  }

  /**
   * Generate disclosure statistics
   */
  getDisclosureStatistics(userId: string): { totalCreators: number; totalDisclosuresSent: number; averageAcknowledgmentRate: number; lastDisclosureDate: Date | null } {
    let totalCreators = 0;
    let totalDisclosuresSent = 0;
    let totalAcknowledged = 0;
    let lastDisclosureDate: Date | null = null;

    for (const [key, history] of this.disclosureHistory.entries()) {
      if (key.startsWith(`${userId}_`)) {
        totalCreators++;
        totalDisclosuresSent += history.length;

        for (const disclosure of history) {
          if (this.acknowledgedDisclosures.has(disclosure.disclosureId)) {
            totalAcknowledged++;
          }
          if (!lastDisclosureDate || new Date(disclosure.sentAt) > lastDisclosureDate) {
            lastDisclosureDate = new Date(disclosure.sentAt);
          }
        }
      }
    }

    const averageAcknowledgmentRate = totalDisclosuresSent > 0 ? (totalAcknowledged / totalDisclosuresSent) * 100 : 0;

    return {
      totalCreators,
      totalDisclosuresSent,
      averageAcknowledgmentRate: Math.round(averageAcknowledgmentRate * 100) / 100,
      lastDisclosureDate,
    };
  }
}

export const dailyDisclosureService = new DailyDisclosureService();
