/** Warm header — shown once at the top of every screen. */
export const PLATFORM_DISCLOSURE_TOP =
  "Thank you for being here · We're grateful you're part of UR";

/** Soft legal footer — shown once at the bottom of every screen. */
export const PLATFORM_DISCLOSURE_BOTTOM =
  "You're chatting with AI companions · Offers may appear · UR may earn a commission on purchases you choose · For education & entertainment, not professional advice";

/** One-line summary for inline use (feeds, cards). */
export const PLATFORM_DISCLOSURE_SHORT =
  "AI-powered · Offers may appear · UR may earn a commission on qualifying purchases";

export const PLATFORM_DISCLOSURE_FULL =
  "You are communicating with artificial intelligence (AI), not real people. " +
  "AI specialists may share promotions, subscriptions, or affiliate links. " +
  "UR Platform may receive a commission on advertisements and qualifying purchases. " +
  "You can decline any offer. Content is for educational and entertainment purposes.";

export const PITCH_ACCEPT_DISCLOSURE =
  "This message is generated by an AI, not a human. UR Platform may receive a commission " +
  "on qualifying purchases and advertisement revenue from offers shown in the app.";

/** Shown immediately BEFORE an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_BEFORE_TEXT =
  "Affiliate & AI note: This message is AI-generated. The link below may be an advertisement " +
  "or affiliate link. UR Platform may earn a commission if you click or purchase.";

/** Shown immediately AFTER an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_AFTER_TEXT =
  "End of linked offer · AI-generated · UR Platform may receive a commission on qualifying purchases.";

/** Spoken before an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_BEFORE_VOICE =
  "Affiliate and A I disclosure before this link. This message is generated by artificial intelligence. " +
  "U R Platform may earn a commission if you use the following link.";

/** Spoken after an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_AFTER_VOICE =
  "End of affiliate link. This was an A I generated advertisement. U R Platform may receive a commission " +
  "on qualifying purchases.";

/** Shown on public feed posts that contain affiliate or AI-promotional content. */
export const SOCIAL_POST_DISCLOSURE =
  "This post may include AI-assisted or affiliate content. UR Platform may earn a commission on qualifying purchases.";
