/** Required disclosure on all user, creator, and AI-facing pages. */
export const PLATFORM_DISCLOSURE_SHORT =
  "You are chatting with AIs. AIs may show ads & offers. UR Platform earns commission on ads & sales.";

export const PLATFORM_DISCLOSURE_FULL =
  "Notice: You are communicating with artificial intelligence (AI), not real people. " +
  "AI specialists may offer promotions, subscriptions, or affiliate links. " +
  "UR Platform receives a commission on advertisements and qualifying purchases. " +
  "You can decline any offer. Content is for educational and entertainment purposes.";

export const PITCH_ACCEPT_DISCLOSURE =
  "This sales message is generated by an AI, not a human. UR Platform receives a percentage " +
  "of qualifying purchases and advertisement revenue from offers shown in the app.";

/** Shown immediately BEFORE an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_BEFORE_TEXT =
  "⚠️ **Affiliate & AI disclosure (before link):** You are viewing an AI-generated message. " +
  "The link below may be an advertisement or affiliate link. UR Platform may earn a commission " +
  "if you click or purchase. This is not advice from a human.";

/** Shown immediately AFTER an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_AFTER_TEXT =
  "⚠️ **Affiliate & AI disclosure (after link):** End of linked offer. This was spoken/written by " +
  "an AI assistant, not a human. UR Platform may receive a commission on qualifying purchases " +
  "from advertisements and affiliate links.";

/** Spoken before an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_BEFORE_VOICE =
  "Affiliate and A I disclosure before this link. This message is generated by artificial intelligence. " +
  "U R Platform may earn a commission if you use the following link.";

/** Spoken after an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_AFTER_VOICE =
  "End of affiliate link. This was an A I generated advertisement. U R Platform may receive a commission " +
  "on qualifying purchases.";

/** Shown on public feed posts that contain affiliate or AI-promotional content. */
export const SOCIAL_POST_DISCLOSURE =
  "This post may include AI-assisted or affiliate content. UR Platform may earn a commission on qualifying purchases.";
