/** Warm header — shown once at the top of every screen. */
export const PLATFORM_DISCLOSURE_TOP =
  "Thank you for being here · You're on UR Platform · AI-powered experience";

/** Soft legal footer — shown once at the bottom of every screen. */
export const PLATFORM_DISCLOSURE_BOTTOM =
  "You're chatting with AI, not humans · Entertainment & education only · No refunds on AI purchases · " +
  "Zero harassment tolerated (privileges revoked, no refund) · Creator purchases are between you & the creator · UR LLC is not responsible for third-party disputes";

/** One-line summary for inline use (feeds, cards). */
export const PLATFORM_DISCLOSURE_SHORT =
  "AI-powered · Not human professionals · Entertainment & education only · UR may earn a commission on offers";

export const PLATFORM_DISCLOSURE_FULL =
  "You are communicating with artificial intelligence (AI) assistants, not real people or licensed professionals. " +
  "All AI content is for entertainment and educational purposes only. If you want professional advice — legal, medical, tax, financial, or otherwise — consult a qualified licensed expert in your jurisdiction. " +
  "AI specialists may share promotions, subscriptions, or affiliate links. UR Platform may receive a commission on advertisements and qualifying purchases. " +
  "You can decline any offer. $5 purchases are made in the mobile app; all other services are purchased in your web browser.";

/** Compact banner shown above AI chat surfaces. */
export function buildAiChatDisclosure(aiName: string): string {
  return (
    `You're chatting with ${aiName} — an AI assistant, not a human. ` +
    `For entertainment and educational purposes only. ` +
    `If you want professional advice, consult a qualified licensed expert. ` +
    `Offers or affiliate links may appear; UR Platform may earn a commission on qualifying purchases.`
  );
}

/** Appended to default AI welcome messages in chat. */
export const AI_WELCOME_DISCLOSURE_SUFFIX =
  "I'm an AI for entertainment and educational purposes only — not a licensed professional. " +
  "If you want professional advice, please consult a qualified expert. " +
  "I may occasionally share offers or affiliate links; UR Platform may earn a commission.";

export const PITCH_ACCEPT_DISCLOSURE =
  "This message is generated by an AI, not a human salesperson. UR Platform may receive a commission " +
  "on qualifying purchases and advertisement revenue from offers shown in the app. " +
  "Content is for entertainment and educational purposes only.";

/** Shown immediately BEFORE an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_BEFORE_TEXT =
  "Affiliate & AI disclosure: You are reading an AI-generated message, not advice from a human professional. " +
  "The link below may be an advertisement or affiliate link. UR Platform may earn a commission if you click or purchase.";

/** Shown immediately AFTER an affiliate / ad link in text chat. */
export const AFFILIATE_LINK_AFTER_TEXT =
  "End of linked offer · AI-generated · Entertainment & education only · UR Platform may receive a commission on qualifying purchases.";

/** Spoken before an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_BEFORE_VOICE =
  "Affiliate and A I disclosure before this link. This message is generated by artificial intelligence, not a human. " +
  "For entertainment and educational purposes only. U R Platform may earn a commission if you use the following link.";

/** Spoken after an affiliate link (voice / TTS). */
export const AFFILIATE_LINK_AFTER_VOICE =
  "End of affiliate link. This was an A I generated advertisement. U R Platform may receive a commission " +
  "on qualifying purchases. Consult a licensed professional if you need professional advice.";

/** Standard disclaimer for legal / attorney AI specialists (client + server reference). */
export const LEGAL_AI_DISCLAIMER =
  "⚠️ AI-Generated Content: You are speaking with an artificial intelligence (AI) assistant, not a licensed attorney or human legal professional. " +
  "Content is for entertainment and educational purposes only. " +
  "If you want professional legal advice, consult a qualified licensed attorney in your jurisdiction. " +
  "Offers or affiliate links may appear; UR Platform may earn a commission on qualifying purchases.";

/** Shown on public feed posts that contain affiliate or AI-promotional content. */
export const SOCIAL_POST_DISCLOSURE =
  "This post may include AI-assisted or affiliate content. UR Platform may earn a commission on qualifying purchases. " +
  "For entertainment and educational purposes — not professional advice. Harassment is not tolerated; violators lose access without refund.";
